apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: workspace
spec:
  triggers:
    - binding:
        name: simple-binding
      template:
        name: trigger-workspace
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: simple-binding

---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-workspace
spec:
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  1Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline-workspace
        workspaces:
          - name: pipeline-workspace
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-workspace
spec:
  workspaces:
  - name: pipeline-workspace
  tasks:
    - name: task1
      workspaces:
      - name: task-workspace
        workspace: pipeline-workspace          
      taskRef:
        name: task-workspace
    - name: task2
      workspaces:
      - name: task-workspace
        workspace: pipeline-workspace          
      taskRef:
        name: task-workspace
      runAfter:
        - task1

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-workspace
spec:
  workspaces:
  - name: task-workspace 
  steps:
    - name: echoenvvar
      image: ubuntu
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -x
          echo 00 lab3
          WS=$(workspaces.task-workspace.path)
          ls $WS
          cd $WS
          echo hi >> hi
          ls $WS
          cat hi

---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: trigger-two-steps-share-dir
spec:
  triggers:
    - binding:
        name: simple-binding
      template:
        name: trigger-two-steps-share-dir

---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-two-steps-share-dir
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline-two-steps-share-dir
        workspaces:
          - name: pipeline-workspace
            emptyDir: {}

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-two-steps-share-dir
spec:
  workspaces:
  - name: pipeline-workspace
  tasks:
    - name: two-steps-share-dir1
      workspaces:
      - name: task-workspace
        workspace: pipeline-workspace          
      taskRef:
        name: two-steps-share-dir
    - name: two-steps-share-dir2
      workspaces:
      - name: task-workspace
        workspace: pipeline-workspace          
      taskRef:
        name: two-steps-share-dir

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: two-steps-share-dir
spec:
  workspaces:
  - name: task-workspace 
  steps:
    - name: makehi
      image: ubuntu
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -x
          echo 01 lab3
          WS=$(workspaces.task-workspace.path)
          ls $WS
          cd $WS
          echo hi >> hi
          ls $WS
          cat hi
    - name: seehi
      image: ubuntu
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -x
          echo 01 lab3
          WS=$(workspaces.task-workspace.path)
          ls $WS
          cd $WS
          echo hi >> hi
          ls $WS
          cat hi
