apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: workspace
spec:
  triggers:
    - binding:
        name: simple-binding
      template:
        name: trigger-workspace
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: simple-binding

---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-workspace
spec:
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  1Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline-workspace
        workspaces:
          - name: pipeline-workspace
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-workspace
spec:
  workspaces:
  - name: pipeline-workspace
  params:
  - name: repository
    default: https://github.com/powellquiring/tekton.git
  - name: branch
    default: master
  tasks:
  - name: clone
    workspaces:
    - name: artifacts
      workspace: pipeline-workspace          
    taskRef:
      name: clone-repo
    params:
    - name: repository
      value: $(params.repository)
    - name: branch
      value: $(params.branch)
  - name: task1
    workspaces:
    - name: task-workspace
      workspace: pipeline-workspace          
    taskRef:
      name: task-workspace
    runAfter:
    - clone

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-workspace
spec:
  workspaces:
  - name: task-workspace 
  steps:
    - name: echoenvvar
      image: ubuntu
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -x
          WS=$(workspaces.task-workspace.path)
          LAB=lab4-shared-git
          ls $WS
          cd $WS
          ls tekton
          echo testing
          [ "$(./tekton/$LAB/script.bash)" = "worked" ] || exit 1
